package com.salespilot.api.infrastructure.persistence.jpa.entity;
// Generated Mar 24, 2026, 7:05:31 PM by Hibernate Tools 7.2.3.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.util.UUID;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * AiPrompts generated by hbm2java
 */
@Entity
@Table(name="ai_prompts"
    ,catalog="salespilot"
)
public class AiPrompts  implements java.io.Serializable {


     private UUID id;
     private Companies companies;
     private Profiles profiles;
     private String name;
     private String description;
     private String instructions;
     private PromptScope scope;
     private boolean isActive;
     private Timestamp createdAt;
     private Set<PromptAssignments> promptAssignmentses = new HashSet<PromptAssignments>(0);

    public AiPrompts() {
    }

	
    public AiPrompts(UUID id, String name, String instructions, PromptScope scope, boolean isActive, Timestamp createdAt) {
        this.id = id;
        this.name = name;
        this.instructions = instructions;
        this.scope = scope;
        this.isActive = isActive;
        this.createdAt = createdAt;
    }
    public AiPrompts(UUID id, Companies companies, Profiles profiles, String name, String description, String instructions, PromptScope scope, boolean isActive, Timestamp createdAt, Set<PromptAssignments> promptAssignmentses) {
       this.id = id;
       this.companies = companies;
       this.profiles = profiles;
       this.name = name;
       this.description = description;
       this.instructions = instructions;
       this.scope = scope;
       this.isActive = isActive;
       this.createdAt = createdAt;
       this.promptAssignmentses = promptAssignmentses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public UUID getId() {
        return this.id;
    }
    
    public void setId(UUID id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="company_id")
    public Companies getCompanies() {
        return this.companies;
    }
    
    public void setCompanies(Companies companies) {
        this.companies = companies;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="created_by")
    public Profiles getProfiles() {
        return this.profiles;
    }
    
    public void setProfiles(Profiles profiles) {
        this.profiles = profiles;
    }

    
    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="instructions", nullable=false)
    public String getInstructions() {
        return this.instructions;
    }
    
    public void setInstructions(String instructions) {
        this.instructions = instructions;
    }
    @Enumerated(EnumType.STRING)
    @Column(name="scope", nullable=false)
    public PromptScope getScope() {
        return this.scope;
    }
    
    public void setScope(PromptScope scope) {
        this.scope = scope;
    }

    
    @Column(name="is_active", nullable=false)
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false, length=35)
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="aiPrompts")
    public Set<PromptAssignments> getPromptAssignmentses() {
        return this.promptAssignmentses;
    }
    
    public void setPromptAssignmentses(Set<PromptAssignments> promptAssignmentses) {
        this.promptAssignmentses = promptAssignmentses;
    }




}


