package com.salespilot.api.infrastructure.persistence.jpa.entity;
// Generated Mar 24, 2026, 7:05:31 PM by Hibernate Tools 7.2.3.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.util.UUID;
import java.sql.Timestamp;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

/**
 * AuditLogs generated by hbm2java
 */
@Entity
@Table(name="audit_logs"
    ,catalog="salespilot"
)
public class AuditLogs  implements java.io.Serializable {


     private UUID id;
     private Companies companies;
     private Profiles profiles;
     private String action;
     private String entityType;
     private UUID entityId;
     private String payload;
     private Timestamp createdAt;

    public AuditLogs() {
    }

	
    public AuditLogs(UUID id, String action, String entityType, Timestamp createdAt) {
        this.id = id;
        this.action = action;
        this.entityType = entityType;
        this.createdAt = createdAt;
    }
    public AuditLogs(UUID id, Companies companies, Profiles profiles, String action, String entityType, UUID entityId, String payload, Timestamp createdAt) {
       this.id = id;
       this.companies = companies;
       this.profiles = profiles;
       this.action = action;
       this.entityType = entityType;
       this.entityId = entityId;
       this.payload = payload;
       this.createdAt = createdAt;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public UUID getId() {
        return this.id;
    }
    
    public void setId(UUID id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="company_id")
    public Companies getCompanies() {
        return this.companies;
    }
    
    public void setCompanies(Companies companies) {
        this.companies = companies;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="actor_profile_id")
    public Profiles getProfiles() {
        return this.profiles;
    }
    
    public void setProfiles(Profiles profiles) {
        this.profiles = profiles;
    }

    
    @Column(name="action", nullable=false)
    public String getAction() {
        return this.action;
    }
    
    public void setAction(String action) {
        this.action = action;
    }

    
    @Column(name="entity_type", nullable=false)
    public String getEntityType() {
        return this.entityType;
    }
    
    public void setEntityType(String entityType) {
        this.entityType = entityType;
    }

    
    @Column(name="entity_id")
    public UUID getEntityId() {
        return this.entityId;
    }
    
    public void setEntityId(UUID entityId) {
        this.entityId = entityId;
    }
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name="payload", columnDefinition="jsonb")
    public String getPayload() {
        return this.payload;
    }
    
    public void setPayload(String payload) {
        this.payload = payload;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false, length=35)
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }




}


