package com.salespilot.api.infrastructure.persistence.jpa.entity;
// Generated Mar 24, 2026, 7:05:31 PM by Hibernate Tools 7.2.3.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;
import java.util.UUID;
import java.sql.Timestamp;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;
import java.util.HashSet;
import java.util.Set;

/**
 * CompanyMemberships generated by hbm2java
 */
@Entity
@Table(name="company_memberships"
    ,catalog="salespilot"
    , uniqueConstraints = @UniqueConstraint(columnNames={"company_id", "profile_id"}) 
)
public class CompanyMemberships  implements java.io.Serializable {


     private UUID id;
     private Companies companies;
     private CompanyMemberships companyMemberships;
     private Profiles profiles;
     private UserRole role;
     private String jobTitle;
     private String phone;
     private boolean isActive;
     private String preferences;
     private Timestamp createdAt;
     private Timestamp updatedAt;
     private Set<Meetings> meetingsesForSellerMembershipId = new HashSet<Meetings>(0);
     private Set<Meetings> meetingsesForManagerMembershipId = new HashSet<Meetings>(0);
     private Set<CompanyMemberships> companyMembershipses = new HashSet<CompanyMemberships>(0);
     private Set<PromptAssignments> promptAssignmentses = new HashSet<PromptAssignments>(0);

    public CompanyMemberships() {
    }

	
    public CompanyMemberships(UUID id, Companies companies, Profiles profiles, UserRole role, boolean isActive, String preferences, Timestamp createdAt, Timestamp updatedAt) {
        this.id = id;
        this.companies = companies;
        this.profiles = profiles;
        this.role = role;
        this.isActive = isActive;
        this.preferences = preferences;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
    public CompanyMemberships(UUID id, Companies companies, CompanyMemberships companyMemberships, Profiles profiles, UserRole role, String jobTitle, String phone, boolean isActive, String preferences, Timestamp createdAt, Timestamp updatedAt, Set<Meetings> meetingsesForSellerMembershipId, Set<Meetings> meetingsesForManagerMembershipId, Set<CompanyMemberships> companyMembershipses, Set<PromptAssignments> promptAssignmentses) {
       this.id = id;
       this.companies = companies;
       this.companyMemberships = companyMemberships;
       this.profiles = profiles;
       this.role = role;
       this.jobTitle = jobTitle;
       this.phone = phone;
       this.isActive = isActive;
       this.preferences = preferences;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.meetingsesForSellerMembershipId = meetingsesForSellerMembershipId;
       this.meetingsesForManagerMembershipId = meetingsesForManagerMembershipId;
       this.companyMembershipses = companyMembershipses;
       this.promptAssignmentses = promptAssignmentses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public UUID getId() {
        return this.id;
    }
    
    public void setId(UUID id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="company_id", nullable=false)
    public Companies getCompanies() {
        return this.companies;
    }
    
    public void setCompanies(Companies companies) {
        this.companies = companies;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="manager_membership_id")
    public CompanyMemberships getCompanyMemberships() {
        return this.companyMemberships;
    }
    
    public void setCompanyMemberships(CompanyMemberships companyMemberships) {
        this.companyMemberships = companyMemberships;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="profile_id", nullable=false)
    public Profiles getProfiles() {
        return this.profiles;
    }
    
    public void setProfiles(Profiles profiles) {
        this.profiles = profiles;
    }
    @Enumerated(EnumType.STRING)
    @Column(name="role", nullable=false)
    public UserRole getRole() {
        return this.role;
    }
    
    public void setRole(UserRole role) {
        this.role = role;
    }

    
    @Column(name="job_title")
    public String getJobTitle() {
        return this.jobTitle;
    }
    
    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle;
    }

    
    @Column(name="phone")
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="is_active", nullable=false)
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name="preferences", nullable=false, columnDefinition="jsonb")
    public String getPreferences() {
        return this.preferences;
    }
    
    public void setPreferences(String preferences) {
        this.preferences = preferences;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false, length=35)
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at", nullable=false, length=35)
    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="companyMembershipsBySellerMembershipId")
    public Set<Meetings> getMeetingsesForSellerMembershipId() {
        return this.meetingsesForSellerMembershipId;
    }
    
    public void setMeetingsesForSellerMembershipId(Set<Meetings> meetingsesForSellerMembershipId) {
        this.meetingsesForSellerMembershipId = meetingsesForSellerMembershipId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="companyMembershipsByManagerMembershipId")
    public Set<Meetings> getMeetingsesForManagerMembershipId() {
        return this.meetingsesForManagerMembershipId;
    }
    
    public void setMeetingsesForManagerMembershipId(Set<Meetings> meetingsesForManagerMembershipId) {
        this.meetingsesForManagerMembershipId = meetingsesForManagerMembershipId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="companyMemberships")
    public Set<CompanyMemberships> getCompanyMembershipses() {
        return this.companyMembershipses;
    }
    
    public void setCompanyMembershipses(Set<CompanyMemberships> companyMembershipses) {
        this.companyMembershipses = companyMembershipses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="companyMemberships")
    public Set<PromptAssignments> getPromptAssignmentses() {
        return this.promptAssignmentses;
    }
    
    public void setPromptAssignmentses(Set<PromptAssignments> promptAssignmentses) {
        this.promptAssignmentses = promptAssignmentses;
    }




}


