package com.salespilot.api.infrastructure.persistence.jpa.entity;
// Generated Mar 24, 2026, 7:05:31 PM by Hibernate Tools 7.2.3.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;
import java.util.UUID;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Companies generated by hbm2java
 */
@Entity
@Table(name="companies"
    ,catalog="salespilot"
    , uniqueConstraints = @UniqueConstraint(columnNames="cnpj") 
)
public class Companies  implements java.io.Serializable {


     private UUID id;
     private String name;
     private String cnpj;
     private CompanyStatus status;
     private int maxSellers;
     private int maxManagers;
     private String notes;
     private Timestamp createdAt;
     private Timestamp updatedAt;
     private Set<PromptAssignments> promptAssignmentses = new HashSet<PromptAssignments>(0);
     private Set<CompanySubscriptions> companySubscriptionses = new HashSet<CompanySubscriptions>(0);
     private Set<CompanyMemberships> companyMembershipses = new HashSet<CompanyMemberships>(0);
     private Set<AuditLogs> auditLogses = new HashSet<AuditLogs>(0);
     private Set<AiPrompts> aiPromptses = new HashSet<AiPrompts>(0);
     private Set<Meetings> meetingses = new HashSet<Meetings>(0);

    public Companies() {
    }

	
    public Companies(UUID id, String name, CompanyStatus status, int maxSellers, int maxManagers, Timestamp createdAt, Timestamp updatedAt) {
        this.id = id;
        this.name = name;
        this.status = status;
        this.maxSellers = maxSellers;
        this.maxManagers = maxManagers;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
    public Companies(UUID id, String name, String cnpj, CompanyStatus status, int maxSellers, int maxManagers, String notes, Timestamp createdAt, Timestamp updatedAt, Set<PromptAssignments> promptAssignmentses, Set<CompanySubscriptions> companySubscriptionses, Set<CompanyMemberships> companyMembershipses, Set<AuditLogs> auditLogses, Set<AiPrompts> aiPromptses, Set<Meetings> meetingses) {
       this.id = id;
       this.name = name;
       this.cnpj = cnpj;
       this.status = status;
       this.maxSellers = maxSellers;
       this.maxManagers = maxManagers;
       this.notes = notes;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.promptAssignmentses = promptAssignmentses;
       this.companySubscriptionses = companySubscriptionses;
       this.companyMembershipses = companyMembershipses;
       this.auditLogses = auditLogses;
       this.aiPromptses = aiPromptses;
       this.meetingses = meetingses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public UUID getId() {
        return this.id;
    }
    
    public void setId(UUID id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="cnpj", unique=true)
    public String getCnpj() {
        return this.cnpj;
    }
    
    public void setCnpj(String cnpj) {
        this.cnpj = cnpj;
    }
    @Enumerated(EnumType.STRING)
    @Column(name="status", nullable=false)
    public CompanyStatus getStatus() {
        return this.status;
    }
    
    public void setStatus(CompanyStatus status) {
        this.status = status;
    }

    
    @Column(name="max_sellers", nullable=false)
    public int getMaxSellers() {
        return this.maxSellers;
    }
    
    public void setMaxSellers(int maxSellers) {
        this.maxSellers = maxSellers;
    }

    
    @Column(name="max_managers", nullable=false)
    public int getMaxManagers() {
        return this.maxManagers;
    }
    
    public void setMaxManagers(int maxManagers) {
        this.maxManagers = maxManagers;
    }

    
    @Column(name="notes")
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false, length=35)
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at", nullable=false, length=35)
    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="companies")
    public Set<PromptAssignments> getPromptAssignmentses() {
        return this.promptAssignmentses;
    }
    
    public void setPromptAssignmentses(Set<PromptAssignments> promptAssignmentses) {
        this.promptAssignmentses = promptAssignmentses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="companies")
    public Set<CompanySubscriptions> getCompanySubscriptionses() {
        return this.companySubscriptionses;
    }
    
    public void setCompanySubscriptionses(Set<CompanySubscriptions> companySubscriptionses) {
        this.companySubscriptionses = companySubscriptionses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="companies")
    public Set<CompanyMemberships> getCompanyMembershipses() {
        return this.companyMembershipses;
    }
    
    public void setCompanyMembershipses(Set<CompanyMemberships> companyMembershipses) {
        this.companyMembershipses = companyMembershipses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="companies")
    public Set<AuditLogs> getAuditLogses() {
        return this.auditLogses;
    }
    
    public void setAuditLogses(Set<AuditLogs> auditLogses) {
        this.auditLogses = auditLogses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="companies")
    public Set<AiPrompts> getAiPromptses() {
        return this.aiPromptses;
    }
    
    public void setAiPromptses(Set<AiPrompts> aiPromptses) {
        this.aiPromptses = aiPromptses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="companies")
    public Set<Meetings> getMeetingses() {
        return this.meetingses;
    }
    
    public void setMeetingses(Set<Meetings> meetingses) {
        this.meetingses = meetingses;
    }




}


