package com.salespilot.api.infrastructure.persistence.jpa.entity;
// Generated Mar 24, 2026, 7:05:31 PM by Hibernate Tools 7.2.3.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.util.UUID;
import java.sql.Date;
import java.sql.Timestamp;

/**
 * CompanySubscriptions generated by hbm2java
 */
@Entity
@Table(name="company_subscriptions"
    ,catalog="salespilot"
)
public class CompanySubscriptions  implements java.io.Serializable {


     private UUID id;
     private Companies companies;
     private SubscriptionPlans subscriptionPlans;
     private SubscriptionStatus status;
     private Timestamp startsAt;
     private Timestamp endsAt;
     private Date renewalDate;
     private Integer priceCents;
     private Timestamp createdAt;

    public CompanySubscriptions() {
    }

	
    public CompanySubscriptions(UUID id, Companies companies, SubscriptionPlans subscriptionPlans, SubscriptionStatus status, Timestamp createdAt) {
        this.id = id;
        this.companies = companies;
        this.subscriptionPlans = subscriptionPlans;
        this.status = status;
        this.createdAt = createdAt;
    }
    public CompanySubscriptions(UUID id, Companies companies, SubscriptionPlans subscriptionPlans, SubscriptionStatus status, Timestamp startsAt, Timestamp endsAt, Date renewalDate, Integer priceCents, Timestamp createdAt) {
       this.id = id;
       this.companies = companies;
       this.subscriptionPlans = subscriptionPlans;
       this.status = status;
       this.startsAt = startsAt;
       this.endsAt = endsAt;
       this.renewalDate = renewalDate;
       this.priceCents = priceCents;
       this.createdAt = createdAt;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public UUID getId() {
        return this.id;
    }
    
    public void setId(UUID id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="company_id", nullable=false)
    public Companies getCompanies() {
        return this.companies;
    }
    
    public void setCompanies(Companies companies) {
        this.companies = companies;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="plan_id", nullable=false)
    public SubscriptionPlans getSubscriptionPlans() {
        return this.subscriptionPlans;
    }
    
    public void setSubscriptionPlans(SubscriptionPlans subscriptionPlans) {
        this.subscriptionPlans = subscriptionPlans;
    }
    @Enumerated(EnumType.STRING)
    @Column(name="status", nullable=false)
    public SubscriptionStatus getStatus() {
        return this.status;
    }
    
    public void setStatus(SubscriptionStatus status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="starts_at", length=35)
    public Timestamp getStartsAt() {
        return this.startsAt;
    }
    
    public void setStartsAt(Timestamp startsAt) {
        this.startsAt = startsAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ends_at", length=35)
    public Timestamp getEndsAt() {
        return this.endsAt;
    }
    
    public void setEndsAt(Timestamp endsAt) {
        this.endsAt = endsAt;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="renewal_date", length=13)
    public Date getRenewalDate() {
        return this.renewalDate;
    }
    
    public void setRenewalDate(Date renewalDate) {
        this.renewalDate = renewalDate;
    }

    
    @Column(name="price_cents")
    public Integer getPriceCents() {
        return this.priceCents;
    }
    
    public void setPriceCents(Integer priceCents) {
        this.priceCents = priceCents;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false, length=35)
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }




}


