package com.salespilot.api.infrastructure.persistence.jpa.entity;
// Generated Mar 24, 2026, 7:05:31 PM by Hibernate Tools 7.2.3.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.util.UUID;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Meetings generated by hbm2java
 */
@Entity
@Table(name="meetings"
    ,catalog="salespilot"
)
public class Meetings  implements java.io.Serializable {


     private UUID id;
     private Companies companies;
     private CompanyMemberships companyMembershipsBySellerMembershipId;
     private CompanyMemberships companyMembershipsByManagerMembershipId;
     private String title;
     private Timestamp scheduledFor;
     private Timestamp startedAt;
     private Timestamp endedAt;
     private Integer durationSeconds;
     private MeetingStatus status;
     private MeetingResult result;
     private String meetingType;
     private String clientName;
     private String clientCompanyName;
     private String clientSector;
     private String objective;
     private String customerPains;
     private String previousInteractions;
     private String competitors;
     private String transcriptStoragePath;
     private String audioStoragePath;
     private String summaryStoragePath;
     private Timestamp processedAt;
     private Timestamp createdAt;
     private Timestamp updatedAt;
     private Set<MeetingPostAnalysis> meetingPostAnalysises = new HashSet<MeetingPostAnalysis>(0);
     private Set<MeetingRealtimeInsights> meetingRealtimeInsightses = new HashSet<MeetingRealtimeInsights>(0);

    public Meetings() {
    }

	
    public Meetings(UUID id, Companies companies, CompanyMemberships companyMembershipsBySellerMembershipId, MeetingStatus status, MeetingResult result, Timestamp createdAt, Timestamp updatedAt) {
        this.id = id;
        this.companies = companies;
        this.companyMembershipsBySellerMembershipId = companyMembershipsBySellerMembershipId;
        this.status = status;
        this.result = result;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
    public Meetings(UUID id, Companies companies, CompanyMemberships companyMembershipsBySellerMembershipId, CompanyMemberships companyMembershipsByManagerMembershipId, String title, Timestamp scheduledFor, Timestamp startedAt, Timestamp endedAt, Integer durationSeconds, MeetingStatus status, MeetingResult result, String meetingType, String clientName, String clientCompanyName, String clientSector, String objective, String customerPains, String previousInteractions, String competitors, String transcriptStoragePath, String audioStoragePath, String summaryStoragePath, Timestamp processedAt, Timestamp createdAt, Timestamp updatedAt, Set<MeetingPostAnalysis> meetingPostAnalysises, Set<MeetingRealtimeInsights> meetingRealtimeInsightses) {
       this.id = id;
       this.companies = companies;
       this.companyMembershipsBySellerMembershipId = companyMembershipsBySellerMembershipId;
       this.companyMembershipsByManagerMembershipId = companyMembershipsByManagerMembershipId;
       this.title = title;
       this.scheduledFor = scheduledFor;
       this.startedAt = startedAt;
       this.endedAt = endedAt;
       this.durationSeconds = durationSeconds;
       this.status = status;
       this.result = result;
       this.meetingType = meetingType;
       this.clientName = clientName;
       this.clientCompanyName = clientCompanyName;
       this.clientSector = clientSector;
       this.objective = objective;
       this.customerPains = customerPains;
       this.previousInteractions = previousInteractions;
       this.competitors = competitors;
       this.transcriptStoragePath = transcriptStoragePath;
       this.audioStoragePath = audioStoragePath;
       this.summaryStoragePath = summaryStoragePath;
       this.processedAt = processedAt;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.meetingPostAnalysises = meetingPostAnalysises;
       this.meetingRealtimeInsightses = meetingRealtimeInsightses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public UUID getId() {
        return this.id;
    }
    
    public void setId(UUID id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="company_id", nullable=false)
    public Companies getCompanies() {
        return this.companies;
    }
    
    public void setCompanies(Companies companies) {
        this.companies = companies;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="seller_membership_id", nullable=false)
    public CompanyMemberships getCompanyMembershipsBySellerMembershipId() {
        return this.companyMembershipsBySellerMembershipId;
    }
    
    public void setCompanyMembershipsBySellerMembershipId(CompanyMemberships companyMembershipsBySellerMembershipId) {
        this.companyMembershipsBySellerMembershipId = companyMembershipsBySellerMembershipId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="manager_membership_id")
    public CompanyMemberships getCompanyMembershipsByManagerMembershipId() {
        return this.companyMembershipsByManagerMembershipId;
    }
    
    public void setCompanyMembershipsByManagerMembershipId(CompanyMemberships companyMembershipsByManagerMembershipId) {
        this.companyMembershipsByManagerMembershipId = companyMembershipsByManagerMembershipId;
    }

    
    @Column(name="title")
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="scheduled_for", length=35)
    public Timestamp getScheduledFor() {
        return this.scheduledFor;
    }
    
    public void setScheduledFor(Timestamp scheduledFor) {
        this.scheduledFor = scheduledFor;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="started_at", length=35)
    public Timestamp getStartedAt() {
        return this.startedAt;
    }
    
    public void setStartedAt(Timestamp startedAt) {
        this.startedAt = startedAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ended_at", length=35)
    public Timestamp getEndedAt() {
        return this.endedAt;
    }
    
    public void setEndedAt(Timestamp endedAt) {
        this.endedAt = endedAt;
    }

    
    @Column(name="duration_seconds")
    public Integer getDurationSeconds() {
        return this.durationSeconds;
    }
    
    public void setDurationSeconds(Integer durationSeconds) {
        this.durationSeconds = durationSeconds;
    }
    @Enumerated(EnumType.STRING)
    @Column(name="status", nullable=false)
    public MeetingStatus getStatus() {
        return this.status;
    }
    
    public void setStatus(MeetingStatus status) {
        this.status = status;
    }
    @Enumerated(EnumType.STRING)
    @Column(name="result", nullable=false)
    public MeetingResult getResult() {
        return this.result;
    }
    
    public void setResult(MeetingResult result) {
        this.result = result;
    }

    
    @Column(name="meeting_type")
    public String getMeetingType() {
        return this.meetingType;
    }
    
    public void setMeetingType(String meetingType) {
        this.meetingType = meetingType;
    }

    
    @Column(name="client_name")
    public String getClientName() {
        return this.clientName;
    }
    
    public void setClientName(String clientName) {
        this.clientName = clientName;
    }

    
    @Column(name="client_company_name")
    public String getClientCompanyName() {
        return this.clientCompanyName;
    }
    
    public void setClientCompanyName(String clientCompanyName) {
        this.clientCompanyName = clientCompanyName;
    }

    
    @Column(name="client_sector")
    public String getClientSector() {
        return this.clientSector;
    }
    
    public void setClientSector(String clientSector) {
        this.clientSector = clientSector;
    }

    
    @Column(name="objective")
    public String getObjective() {
        return this.objective;
    }
    
    public void setObjective(String objective) {
        this.objective = objective;
    }

    
    @Column(name="customer_pains")
    public String getCustomerPains() {
        return this.customerPains;
    }
    
    public void setCustomerPains(String customerPains) {
        this.customerPains = customerPains;
    }

    
    @Column(name="previous_interactions")
    public String getPreviousInteractions() {
        return this.previousInteractions;
    }
    
    public void setPreviousInteractions(String previousInteractions) {
        this.previousInteractions = previousInteractions;
    }

    
    @Column(name="competitors")
    public String getCompetitors() {
        return this.competitors;
    }
    
    public void setCompetitors(String competitors) {
        this.competitors = competitors;
    }

    
    @Column(name="transcript_storage_path")
    public String getTranscriptStoragePath() {
        return this.transcriptStoragePath;
    }
    
    public void setTranscriptStoragePath(String transcriptStoragePath) {
        this.transcriptStoragePath = transcriptStoragePath;
    }

    
    @Column(name="audio_storage_path")
    public String getAudioStoragePath() {
        return this.audioStoragePath;
    }
    
    public void setAudioStoragePath(String audioStoragePath) {
        this.audioStoragePath = audioStoragePath;
    }

    
    @Column(name="summary_storage_path")
    public String getSummaryStoragePath() {
        return this.summaryStoragePath;
    }
    
    public void setSummaryStoragePath(String summaryStoragePath) {
        this.summaryStoragePath = summaryStoragePath;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="processed_at", length=35)
    public Timestamp getProcessedAt() {
        return this.processedAt;
    }
    
    public void setProcessedAt(Timestamp processedAt) {
        this.processedAt = processedAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false, length=35)
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at", nullable=false, length=35)
    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="meetings")
    public Set<MeetingPostAnalysis> getMeetingPostAnalysises() {
        return this.meetingPostAnalysises;
    }
    
    public void setMeetingPostAnalysises(Set<MeetingPostAnalysis> meetingPostAnalysises) {
        this.meetingPostAnalysises = meetingPostAnalysises;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="meetings")
    public Set<MeetingRealtimeInsights> getMeetingRealtimeInsightses() {
        return this.meetingRealtimeInsightses;
    }
    
    public void setMeetingRealtimeInsightses(Set<MeetingRealtimeInsights> meetingRealtimeInsightses) {
        this.meetingRealtimeInsightses = meetingRealtimeInsightses;
    }




}


