package com.salespilot.api.infrastructure.persistence.jpa.entity;
// Generated Mar 24, 2026, 7:05:31 PM by Hibernate Tools 7.2.3.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.util.UUID;
import java.sql.Timestamp;

/**
 * MeetingRealtimeInsights generated by hbm2java
 */
@Entity
@Table(name="meeting_realtime_insights"
    ,catalog="salespilot"
)
public class MeetingRealtimeInsights  implements java.io.Serializable {


     private UUID id;
     private Meetings meetings;
     private RealtimeInsightType type;
     private String content;
     private Integer sequenceNumber;
     private Timestamp createdAt;

    public MeetingRealtimeInsights() {
    }

	
    public MeetingRealtimeInsights(UUID id, Meetings meetings, RealtimeInsightType type, String content, Timestamp createdAt) {
        this.id = id;
        this.meetings = meetings;
        this.type = type;
        this.content = content;
        this.createdAt = createdAt;
    }
    public MeetingRealtimeInsights(UUID id, Meetings meetings, RealtimeInsightType type, String content, Integer sequenceNumber, Timestamp createdAt) {
       this.id = id;
       this.meetings = meetings;
       this.type = type;
       this.content = content;
       this.sequenceNumber = sequenceNumber;
       this.createdAt = createdAt;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public UUID getId() {
        return this.id;
    }
    
    public void setId(UUID id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="meeting_id", nullable=false)
    public Meetings getMeetings() {
        return this.meetings;
    }
    
    public void setMeetings(Meetings meetings) {
        this.meetings = meetings;
    }
    @Enumerated(EnumType.STRING)
    @Column(name="type", nullable=false)
    public RealtimeInsightType getType() {
        return this.type;
    }
    
    public void setType(RealtimeInsightType type) {
        this.type = type;
    }

    
    @Column(name="content", nullable=false)
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }

    
    @Column(name="sequence_number")
    public Integer getSequenceNumber() {
        return this.sequenceNumber;
    }
    
    public void setSequenceNumber(Integer sequenceNumber) {
        this.sequenceNumber = sequenceNumber;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false, length=35)
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }




}


