package com.salespilot.api.infrastructure.persistence.jpa.entity;
// Generated Mar 24, 2026, 7:05:31 PM by Hibernate Tools 7.2.3.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;
import java.util.UUID;
import java.sql.Timestamp;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

/**
 * MeetingPostAnalysis generated by hbm2java
 */
@Entity
@Table(name="meeting_post_analysis"
    ,catalog="salespilot"
    , uniqueConstraints = @UniqueConstraint(columnNames="meeting_id") 
)
public class MeetingPostAnalysis  implements java.io.Serializable {


     private UUID id;
     private Meetings meetings;
     private String summary;
     private String actionItems;
     private String sentimentAnalysis;
     private String recommendedStrategy;
     private String keyPoints;
     private String possibleObjections;
     private Timestamp generatedAt;

    public MeetingPostAnalysis() {
    }

	
    public MeetingPostAnalysis(UUID id, Meetings meetings, Timestamp generatedAt) {
        this.id = id;
        this.meetings = meetings;
        this.generatedAt = generatedAt;
    }
    public MeetingPostAnalysis(UUID id, Meetings meetings, String summary, String actionItems, String sentimentAnalysis, String recommendedStrategy, String keyPoints, String possibleObjections, Timestamp generatedAt) {
       this.id = id;
       this.meetings = meetings;
       this.summary = summary;
       this.actionItems = actionItems;
       this.sentimentAnalysis = sentimentAnalysis;
       this.recommendedStrategy = recommendedStrategy;
       this.keyPoints = keyPoints;
       this.possibleObjections = possibleObjections;
       this.generatedAt = generatedAt;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public UUID getId() {
        return this.id;
    }
    
    public void setId(UUID id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="meeting_id", unique=true, nullable=false)
    public Meetings getMeetings() {
        return this.meetings;
    }
    
    public void setMeetings(Meetings meetings) {
        this.meetings = meetings;
    }
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name="summary", columnDefinition="jsonb")
    public String getSummary() {
        return this.summary;
    }
    
    public void setSummary(String summary) {
        this.summary = summary;
    }
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name="action_items", columnDefinition="jsonb")
    public String getActionItems() {
        return this.actionItems;
    }
    
    public void setActionItems(String actionItems) {
        this.actionItems = actionItems;
    }
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name="sentiment_analysis", columnDefinition="jsonb")
    public String getSentimentAnalysis() {
        return this.sentimentAnalysis;
    }
    
    public void setSentimentAnalysis(String sentimentAnalysis) {
        this.sentimentAnalysis = sentimentAnalysis;
    }
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name="recommended_strategy", columnDefinition="jsonb")
    public String getRecommendedStrategy() {
        return this.recommendedStrategy;
    }
    
    public void setRecommendedStrategy(String recommendedStrategy) {
        this.recommendedStrategy = recommendedStrategy;
    }
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name="key_points", columnDefinition="jsonb")
    public String getKeyPoints() {
        return this.keyPoints;
    }
    
    public void setKeyPoints(String keyPoints) {
        this.keyPoints = keyPoints;
    }
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name="possible_objections", columnDefinition="jsonb")
    public String getPossibleObjections() {
        return this.possibleObjections;
    }
    
    public void setPossibleObjections(String possibleObjections) {
        this.possibleObjections = possibleObjections;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="generated_at", nullable=false, length=35)
    public Timestamp getGeneratedAt() {
        return this.generatedAt;
    }
    
    public void setGeneratedAt(Timestamp generatedAt) {
        this.generatedAt = generatedAt;
    }




}


