package com.salespilot.api.infrastructure.persistence.jpa.entity;
// Generated Mar 24, 2026, 7:05:31 PM by Hibernate Tools 7.2.3.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.MapsId;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;
import java.util.UUID;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Profiles generated by hbm2java
 */
@Entity
@Table(name="profiles"
    ,catalog="salespilot"
    , uniqueConstraints = @UniqueConstraint(columnNames="email") 
)
public class Profiles  implements java.io.Serializable {


     private UUID id;
     private Users users;
     private String fullName;
     private String email;
     private String avatarUrl;
     private boolean isActive;
     private Timestamp createdAt;
     private Timestamp updatedAt;
     private Set<AiPrompts> aiPromptses = new HashSet<AiPrompts>(0);
     private Set<CompanyMemberships> companyMembershipses = new HashSet<CompanyMemberships>(0);
     private Set<AuditLogs> auditLogses = new HashSet<AuditLogs>(0);

    public Profiles() {
    }

	
    public Profiles(Users users, String fullName, String email, boolean isActive, Timestamp createdAt, Timestamp updatedAt) {
        this.users = users;
        this.fullName = fullName;
        this.email = email;
        this.isActive = isActive;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
    public Profiles(Users users, String fullName, String email, String avatarUrl, boolean isActive, Timestamp createdAt, Timestamp updatedAt, Set<AiPrompts> aiPromptses, Set<CompanyMemberships> companyMembershipses, Set<AuditLogs> auditLogses) {
       this.users = users;
       this.fullName = fullName;
       this.email = email;
       this.avatarUrl = avatarUrl;
       this.isActive = isActive;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.aiPromptses = aiPromptses;
       this.companyMembershipses = companyMembershipses;
       this.auditLogses = auditLogses;
    }
   
    @Id
    
    @Column(name="id", unique=true, nullable=false)
    public UUID getId() {
        return this.id;
    }
    
    public void setId(UUID id) {
        this.id = id;
    }

    @MapsId
    @OneToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id")
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    
    @Column(name="full_name", nullable=false)
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    
    @Column(name="email", unique=true, nullable=false)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="avatar_url")
    public String getAvatarUrl() {
        return this.avatarUrl;
    }
    
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl;
    }

    
    @Column(name="is_active", nullable=false)
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false, length=35)
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at", nullable=false, length=35)
    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="profiles")
    public Set<AiPrompts> getAiPromptses() {
        return this.aiPromptses;
    }
    
    public void setAiPromptses(Set<AiPrompts> aiPromptses) {
        this.aiPromptses = aiPromptses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="profiles")
    public Set<CompanyMemberships> getCompanyMembershipses() {
        return this.companyMembershipses;
    }
    
    public void setCompanyMembershipses(Set<CompanyMemberships> companyMembershipses) {
        this.companyMembershipses = companyMembershipses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="profiles")
    public Set<AuditLogs> getAuditLogses() {
        return this.auditLogses;
    }
    
    public void setAuditLogses(Set<AuditLogs> auditLogses) {
        this.auditLogses = auditLogses;
    }




}

