package com.salespilot.api.infrastructure.persistence.jpa.entity;
// Generated Mar 24, 2026, 7:05:31 PM by Hibernate Tools 7.2.3.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.util.UUID;
import java.sql.Timestamp;

/**
 * PromptAssignments generated by hbm2java
 */
@Entity
@Table(name="prompt_assignments"
    ,catalog="salespilot"
)
public class PromptAssignments  implements java.io.Serializable {


     private UUID id;
     private AiPrompts aiPrompts;
     private Companies companies;
     private CompanyMemberships companyMemberships;
     private Timestamp createdAt;

    public PromptAssignments() {
    }

	
    public PromptAssignments(UUID id, AiPrompts aiPrompts, Companies companies, Timestamp createdAt) {
        this.id = id;
        this.aiPrompts = aiPrompts;
        this.companies = companies;
        this.createdAt = createdAt;
    }
    public PromptAssignments(UUID id, AiPrompts aiPrompts, Companies companies, CompanyMemberships companyMemberships, Timestamp createdAt) {
       this.id = id;
       this.aiPrompts = aiPrompts;
       this.companies = companies;
       this.companyMemberships = companyMemberships;
       this.createdAt = createdAt;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public UUID getId() {
        return this.id;
    }
    
    public void setId(UUID id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="prompt_id", nullable=false)
    public AiPrompts getAiPrompts() {
        return this.aiPrompts;
    }
    
    public void setAiPrompts(AiPrompts aiPrompts) {
        this.aiPrompts = aiPrompts;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="company_id", nullable=false)
    public Companies getCompanies() {
        return this.companies;
    }
    
    public void setCompanies(Companies companies) {
        this.companies = companies;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="membership_id")
    public CompanyMemberships getCompanyMemberships() {
        return this.companyMemberships;
    }
    
    public void setCompanyMemberships(CompanyMemberships companyMemberships) {
        this.companyMemberships = companyMemberships;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false, length=35)
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }




}


