package com.salespilot.api.infrastructure.persistence.jpa.entity;
// Generated Mar 24, 2026, 7:05:31 PM by Hibernate Tools 7.2.3.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;
import java.util.UUID;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * SubscriptionPlans generated by hbm2java
 */
@Entity
@Table(name="subscription_plans"
    ,catalog="salespilot"
    , uniqueConstraints = @UniqueConstraint(columnNames="name") 
)
public class SubscriptionPlans  implements java.io.Serializable {


     private UUID id;
     private String name;
     private String description;
     private int maxManagers;
     private int maxSellers;
     private boolean hasRealtimeInsights;
     private boolean hasPostMeetingSummary;
     private boolean hasDashboard;
     private boolean isActive;
     private Timestamp createdAt;
     private Set<CompanySubscriptions> companySubscriptionses = new HashSet<CompanySubscriptions>(0);

    public SubscriptionPlans() {
    }

	
    public SubscriptionPlans(UUID id, String name, int maxManagers, int maxSellers, boolean hasRealtimeInsights, boolean hasPostMeetingSummary, boolean hasDashboard, boolean isActive, Timestamp createdAt) {
        this.id = id;
        this.name = name;
        this.maxManagers = maxManagers;
        this.maxSellers = maxSellers;
        this.hasRealtimeInsights = hasRealtimeInsights;
        this.hasPostMeetingSummary = hasPostMeetingSummary;
        this.hasDashboard = hasDashboard;
        this.isActive = isActive;
        this.createdAt = createdAt;
    }
    public SubscriptionPlans(UUID id, String name, String description, int maxManagers, int maxSellers, boolean hasRealtimeInsights, boolean hasPostMeetingSummary, boolean hasDashboard, boolean isActive, Timestamp createdAt, Set<CompanySubscriptions> companySubscriptionses) {
       this.id = id;
       this.name = name;
       this.description = description;
       this.maxManagers = maxManagers;
       this.maxSellers = maxSellers;
       this.hasRealtimeInsights = hasRealtimeInsights;
       this.hasPostMeetingSummary = hasPostMeetingSummary;
       this.hasDashboard = hasDashboard;
       this.isActive = isActive;
       this.createdAt = createdAt;
       this.companySubscriptionses = companySubscriptionses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public UUID getId() {
        return this.id;
    }
    
    public void setId(UUID id) {
        this.id = id;
    }

    
    @Column(name="name", unique=true, nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="max_managers", nullable=false)
    public int getMaxManagers() {
        return this.maxManagers;
    }
    
    public void setMaxManagers(int maxManagers) {
        this.maxManagers = maxManagers;
    }

    
    @Column(name="max_sellers", nullable=false)
    public int getMaxSellers() {
        return this.maxSellers;
    }
    
    public void setMaxSellers(int maxSellers) {
        this.maxSellers = maxSellers;
    }

    
    @Column(name="has_realtime_insights", nullable=false)
    public boolean isHasRealtimeInsights() {
        return this.hasRealtimeInsights;
    }
    
    public void setHasRealtimeInsights(boolean hasRealtimeInsights) {
        this.hasRealtimeInsights = hasRealtimeInsights;
    }

    
    @Column(name="has_post_meeting_summary", nullable=false)
    public boolean isHasPostMeetingSummary() {
        return this.hasPostMeetingSummary;
    }
    
    public void setHasPostMeetingSummary(boolean hasPostMeetingSummary) {
        this.hasPostMeetingSummary = hasPostMeetingSummary;
    }

    
    @Column(name="has_dashboard", nullable=false)
    public boolean isHasDashboard() {
        return this.hasDashboard;
    }
    
    public void setHasDashboard(boolean hasDashboard) {
        this.hasDashboard = hasDashboard;
    }

    
    @Column(name="is_active", nullable=false)
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false, length=35)
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="subscriptionPlans")
    public Set<CompanySubscriptions> getCompanySubscriptionses() {
        return this.companySubscriptionses;
    }
    
    public void setCompanySubscriptionses(Set<CompanySubscriptions> companySubscriptionses) {
        this.companySubscriptionses = companySubscriptionses;
    }




}


