package com.salespilot.api.infrastructure.persistence.jpa.entity;
// Generated Mar 24, 2026, 7:05:31 PM by Hibernate Tools 7.2.3.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;
import java.util.UUID;
import java.sql.Timestamp;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users"
    ,schema="auth"
    ,catalog="salespilot"
    , uniqueConstraints = {@UniqueConstraint(columnNames="confirmation_token"), @UniqueConstraint(columnNames="email_change_token_current"), @UniqueConstraint(columnNames="email_change_token_new"), @UniqueConstraint(columnNames="reauthentication_token"), @UniqueConstraint(columnNames="recovery_token"), @UniqueConstraint(columnNames="email"), @UniqueConstraint(columnNames="phone")} 
)
public class Users  implements java.io.Serializable {


     private UUID id;
     private UUID instanceId;
     private String aud;
     private String role;
     private String email;
     private String encryptedPassword;
     private Timestamp emailConfirmedAt;
     private Timestamp invitedAt;
     private String confirmationToken;
     private Timestamp confirmationSentAt;
     private String recoveryToken;
     private Timestamp recoverySentAt;
     private String emailChangeTokenNew;
     private String emailChange;
     private Timestamp emailChangeSentAt;
     private Timestamp lastSignInAt;
     private String rawAppMetaData;
     private String rawUserMetaData;
     private Boolean isSuperAdmin;
     private Timestamp createdAt;
     private Timestamp updatedAt;
     private String phone;
     private Timestamp phoneConfirmedAt;
     private String phoneChange;
     private String phoneChangeToken;
     private Timestamp phoneChangeSentAt;
     private Timestamp confirmedAt;
     private String emailChangeTokenCurrent;
     private Short emailChangeConfirmStatus;
     private Timestamp bannedUntil;
     private String reauthenticationToken;
     private Timestamp reauthenticationSentAt;
     private boolean isSsoUser;
     private Timestamp deletedAt;
     private boolean isAnonymous;
     private Profiles profiles;

    public Users() {
    }

	
    public Users(UUID id, boolean isSsoUser, boolean isAnonymous) {
        this.id = id;
        this.isSsoUser = isSsoUser;
        this.isAnonymous = isAnonymous;
    }
    public Users(UUID id, UUID instanceId, String aud, String role, String email, String encryptedPassword, Timestamp emailConfirmedAt, Timestamp invitedAt, String confirmationToken, Timestamp confirmationSentAt, String recoveryToken, Timestamp recoverySentAt, String emailChangeTokenNew, String emailChange, Timestamp emailChangeSentAt, Timestamp lastSignInAt, String rawAppMetaData, String rawUserMetaData, Boolean isSuperAdmin, Timestamp createdAt, Timestamp updatedAt, String phone, Timestamp phoneConfirmedAt, String phoneChange, String phoneChangeToken, Timestamp phoneChangeSentAt, Timestamp confirmedAt, String emailChangeTokenCurrent, Short emailChangeConfirmStatus, Timestamp bannedUntil, String reauthenticationToken, Timestamp reauthenticationSentAt, boolean isSsoUser, Timestamp deletedAt, boolean isAnonymous, Profiles profiles) {
       this.id = id;
       this.instanceId = instanceId;
       this.aud = aud;
       this.role = role;
       this.email = email;
       this.encryptedPassword = encryptedPassword;
       this.emailConfirmedAt = emailConfirmedAt;
       this.invitedAt = invitedAt;
       this.confirmationToken = confirmationToken;
       this.confirmationSentAt = confirmationSentAt;
       this.recoveryToken = recoveryToken;
       this.recoverySentAt = recoverySentAt;
       this.emailChangeTokenNew = emailChangeTokenNew;
       this.emailChange = emailChange;
       this.emailChangeSentAt = emailChangeSentAt;
       this.lastSignInAt = lastSignInAt;
       this.rawAppMetaData = rawAppMetaData;
       this.rawUserMetaData = rawUserMetaData;
       this.isSuperAdmin = isSuperAdmin;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.phone = phone;
       this.phoneConfirmedAt = phoneConfirmedAt;
       this.phoneChange = phoneChange;
       this.phoneChangeToken = phoneChangeToken;
       this.phoneChangeSentAt = phoneChangeSentAt;
       this.confirmedAt = confirmedAt;
       this.emailChangeTokenCurrent = emailChangeTokenCurrent;
       this.emailChangeConfirmStatus = emailChangeConfirmStatus;
       this.bannedUntil = bannedUntil;
       this.reauthenticationToken = reauthenticationToken;
       this.reauthenticationSentAt = reauthenticationSentAt;
       this.isSsoUser = isSsoUser;
       this.deletedAt = deletedAt;
       this.isAnonymous = isAnonymous;
       this.profiles = profiles;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public UUID getId() {
        return this.id;
    }
    
    public void setId(UUID id) {
        this.id = id;
    }

    
    @Column(name="instance_id")
    public UUID getInstanceId() {
        return this.instanceId;
    }
    
    public void setInstanceId(UUID instanceId) {
        this.instanceId = instanceId;
    }

    
    @Column(name="aud", length=255)
    public String getAud() {
        return this.aud;
    }
    
    public void setAud(String aud) {
        this.aud = aud;
    }

    
    @Column(name="role", length=255)
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }

    
    @Column(name="email", unique=true, length=255)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="encrypted_password", length=255)
    public String getEncryptedPassword() {
        return this.encryptedPassword;
    }
    
    public void setEncryptedPassword(String encryptedPassword) {
        this.encryptedPassword = encryptedPassword;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="email_confirmed_at", length=35)
    public Timestamp getEmailConfirmedAt() {
        return this.emailConfirmedAt;
    }
    
    public void setEmailConfirmedAt(Timestamp emailConfirmedAt) {
        this.emailConfirmedAt = emailConfirmedAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="invited_at", length=35)
    public Timestamp getInvitedAt() {
        return this.invitedAt;
    }
    
    public void setInvitedAt(Timestamp invitedAt) {
        this.invitedAt = invitedAt;
    }

    
    @Column(name="confirmation_token", unique=true, length=255)
    public String getConfirmationToken() {
        return this.confirmationToken;
    }
    
    public void setConfirmationToken(String confirmationToken) {
        this.confirmationToken = confirmationToken;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="confirmation_sent_at", length=35)
    public Timestamp getConfirmationSentAt() {
        return this.confirmationSentAt;
    }
    
    public void setConfirmationSentAt(Timestamp confirmationSentAt) {
        this.confirmationSentAt = confirmationSentAt;
    }

    
    @Column(name="recovery_token", unique=true, length=255)
    public String getRecoveryToken() {
        return this.recoveryToken;
    }
    
    public void setRecoveryToken(String recoveryToken) {
        this.recoveryToken = recoveryToken;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="recovery_sent_at", length=35)
    public Timestamp getRecoverySentAt() {
        return this.recoverySentAt;
    }
    
    public void setRecoverySentAt(Timestamp recoverySentAt) {
        this.recoverySentAt = recoverySentAt;
    }

    
    @Column(name="email_change_token_new", unique=true, length=255)
    public String getEmailChangeTokenNew() {
        return this.emailChangeTokenNew;
    }
    
    public void setEmailChangeTokenNew(String emailChangeTokenNew) {
        this.emailChangeTokenNew = emailChangeTokenNew;
    }

    
    @Column(name="email_change", length=255)
    public String getEmailChange() {
        return this.emailChange;
    }
    
    public void setEmailChange(String emailChange) {
        this.emailChange = emailChange;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="email_change_sent_at", length=35)
    public Timestamp getEmailChangeSentAt() {
        return this.emailChangeSentAt;
    }
    
    public void setEmailChangeSentAt(Timestamp emailChangeSentAt) {
        this.emailChangeSentAt = emailChangeSentAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_sign_in_at", length=35)
    public Timestamp getLastSignInAt() {
        return this.lastSignInAt;
    }
    
    public void setLastSignInAt(Timestamp lastSignInAt) {
        this.lastSignInAt = lastSignInAt;
    }
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name="raw_app_meta_data", columnDefinition="jsonb")
    public String getRawAppMetaData() {
        return this.rawAppMetaData;
    }
    
    public void setRawAppMetaData(String rawAppMetaData) {
        this.rawAppMetaData = rawAppMetaData;
    }
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name="raw_user_meta_data", columnDefinition="jsonb")
    public String getRawUserMetaData() {
        return this.rawUserMetaData;
    }
    
    public void setRawUserMetaData(String rawUserMetaData) {
        this.rawUserMetaData = rawUserMetaData;
    }

    
    @Column(name="is_super_admin")
    public Boolean getIsSuperAdmin() {
        return this.isSuperAdmin;
    }
    
    public void setIsSuperAdmin(Boolean isSuperAdmin) {
        this.isSuperAdmin = isSuperAdmin;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", length=35)
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at", length=35)
    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }

    
    @Column(name="phone", unique=true)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="phone_confirmed_at", length=35)
    public Timestamp getPhoneConfirmedAt() {
        return this.phoneConfirmedAt;
    }
    
    public void setPhoneConfirmedAt(Timestamp phoneConfirmedAt) {
        this.phoneConfirmedAt = phoneConfirmedAt;
    }

    
    @Column(name="phone_change")
    public String getPhoneChange() {
        return this.phoneChange;
    }
    
    public void setPhoneChange(String phoneChange) {
        this.phoneChange = phoneChange;
    }

    
    @Column(name="phone_change_token", length=255)
    public String getPhoneChangeToken() {
        return this.phoneChangeToken;
    }
    
    public void setPhoneChangeToken(String phoneChangeToken) {
        this.phoneChangeToken = phoneChangeToken;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="phone_change_sent_at", length=35)
    public Timestamp getPhoneChangeSentAt() {
        return this.phoneChangeSentAt;
    }
    
    public void setPhoneChangeSentAt(Timestamp phoneChangeSentAt) {
        this.phoneChangeSentAt = phoneChangeSentAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="confirmed_at", length=35)
    public Timestamp getConfirmedAt() {
        return this.confirmedAt;
    }
    
    public void setConfirmedAt(Timestamp confirmedAt) {
        this.confirmedAt = confirmedAt;
    }

    
    @Column(name="email_change_token_current", unique=true, length=255)
    public String getEmailChangeTokenCurrent() {
        return this.emailChangeTokenCurrent;
    }
    
    public void setEmailChangeTokenCurrent(String emailChangeTokenCurrent) {
        this.emailChangeTokenCurrent = emailChangeTokenCurrent;
    }

    
    @Column(name="email_change_confirm_status")
    public Short getEmailChangeConfirmStatus() {
        return this.emailChangeConfirmStatus;
    }
    
    public void setEmailChangeConfirmStatus(Short emailChangeConfirmStatus) {
        this.emailChangeConfirmStatus = emailChangeConfirmStatus;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="banned_until", length=35)
    public Timestamp getBannedUntil() {
        return this.bannedUntil;
    }
    
    public void setBannedUntil(Timestamp bannedUntil) {
        this.bannedUntil = bannedUntil;
    }

    
    @Column(name="reauthentication_token", unique=true, length=255)
    public String getReauthenticationToken() {
        return this.reauthenticationToken;
    }
    
    public void setReauthenticationToken(String reauthenticationToken) {
        this.reauthenticationToken = reauthenticationToken;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="reauthentication_sent_at", length=35)
    public Timestamp getReauthenticationSentAt() {
        return this.reauthenticationSentAt;
    }
    
    public void setReauthenticationSentAt(Timestamp reauthenticationSentAt) {
        this.reauthenticationSentAt = reauthenticationSentAt;
    }

    
    @Column(name="is_sso_user", nullable=false)
    public boolean isIsSsoUser() {
        return this.isSsoUser;
    }
    
    public void setIsSsoUser(boolean isSsoUser) {
        this.isSsoUser = isSsoUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="deleted_at", length=35)
    public Timestamp getDeletedAt() {
        return this.deletedAt;
    }
    
    public void setDeletedAt(Timestamp deletedAt) {
        this.deletedAt = deletedAt;
    }

    
    @Column(name="is_anonymous", nullable=false)
    public boolean isIsAnonymous() {
        return this.isAnonymous;
    }
    
    public void setIsAnonymous(boolean isAnonymous) {
        this.isAnonymous = isAnonymous;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="users")
    public Profiles getProfiles() {
        return this.profiles;
    }
    
    public void setProfiles(Profiles profiles) {
        this.profiles = profiles;
    }




}


